// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

// PublicGetCurrencies returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetCurrencies(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetCurrencies", args...)
}

// PublicGetCurrenciesCurrency returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetCurrenciesCurrency(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetCurrenciesCurrency", args...)
}

// PublicGetSymbols returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetSymbols(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetSymbols", args...)
}

// PublicGetMarketOrderbookLevel1 returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketOrderbookLevel1(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketOrderbookLevel1", args...)
}

// PublicGetMarketAllTickers returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketAllTickers(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketAllTickers", args...)
}

// PublicGetMarketStats returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketStats(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketStats", args...)
}

// PublicGetMarkets returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarkets(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarkets", args...)
}

// PublicGetMarketOrderbookLevelLevelLimit returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketOrderbookLevelLevelLimit(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketOrderbookLevelLevelLimit", args...)
}

// PublicGetMarketOrderbookLevel220 returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketOrderbookLevel220(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketOrderbookLevel220", args...)
}

// PublicGetMarketOrderbookLevel2100 returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketOrderbookLevel2100(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketOrderbookLevel2100", args...)
}

// PublicGetMarketHistories returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketHistories(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketHistories", args...)
}

// PublicGetMarketCandles returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarketCandles(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketCandles", args...)
}

// PublicGetPrices returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetPrices(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetPrices", args...)
}

// PublicGetTimestamp returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetTimestamp(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetTimestamp", args...)
}

// PublicGetStatus returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetStatus(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetStatus", args...)
}

// PublicGetMarkPriceSymbolCurrent returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarkPriceSymbolCurrent(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarkPriceSymbolCurrent", args...)
}

// PublicGetMarkPriceAllSymbols returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarkPriceAllSymbols(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarkPriceAllSymbols", args...)
}

// PublicGetMarginConfig returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarginConfig(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarginConfig", args...)
}

// PublicGetAnnouncements returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetAnnouncements(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetAnnouncements", args...)
}

// PublicGetMarginCollateralRatio returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetMarginCollateralRatio(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarginCollateralRatio", args...)
}

// PublicGetConvertSymbol returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetConvertSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetConvertSymbol", args...)
}

// PublicGetConvertCurrencies returns a channel that yields a JSON object.
func (this *CexcCore) PublicGetConvertCurrencies(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetConvertCurrencies", args...)
}

// PublicPostBulletPublic returns a channel that yields a JSON object.
func (this *CexcCore) PublicPostBulletPublic(args ...any) <-chan any {
	return this.callEndpointAsync("publicPostBulletPublic", args...)
}

// PrivateGetUserInfo returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetUserInfo(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetUserInfo", args...)
}

// PrivateGetUserApiKey returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetUserApiKey(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetUserApiKey", args...)
}

// PrivateGetAccounts returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetAccounts(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetAccounts", args...)
}

// PrivateGetAccountsAccountId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetAccountsAccountId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetAccountsAccountId", args...)
}

// PrivateGetAccountsLedgers returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetAccountsLedgers(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetAccountsLedgers", args...)
}

// PrivateGetHfAccountsLedgers returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfAccountsLedgers(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfAccountsLedgers", args...)
}

// PrivateGetHfMarginAccountLedgers returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginAccountLedgers(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginAccountLedgers", args...)
}

// PrivateGetTransactionHistory returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetTransactionHistory(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetTransactionHistory", args...)
}

// PrivateGetSubUser returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetSubUser(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetSubUser", args...)
}

// PrivateGetSubAccountsSubUserId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetSubAccountsSubUserId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetSubAccountsSubUserId", args...)
}

// PrivateGetSubAccounts returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetSubAccounts(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetSubAccounts", args...)
}

// PrivateGetSubApiKey returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetSubApiKey(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetSubApiKey", args...)
}

// PrivateGetMarginAccount returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarginAccount(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarginAccount", args...)
}

// PrivateGetMarginAccounts returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarginAccounts(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarginAccounts", args...)
}

// PrivateGetIsolatedAccounts returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetIsolatedAccounts(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetIsolatedAccounts", args...)
}

// PrivateGetDepositAddresses returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetDepositAddresses(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetDepositAddresses", args...)
}

// PrivateGetDeposits returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetDeposits(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetDeposits", args...)
}

// PrivateGetHistDeposits returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHistDeposits(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHistDeposits", args...)
}

// PrivateGetWithdrawals returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetWithdrawals(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetWithdrawals", args...)
}

// PrivateGetHistWithdrawals returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHistWithdrawals(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHistWithdrawals", args...)
}

// PrivateGetWithdrawalsQuotas returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetWithdrawalsQuotas(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetWithdrawalsQuotas", args...)
}

// PrivateGetAccountsTransferable returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetAccountsTransferable(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetAccountsTransferable", args...)
}

// PrivateGetTransferList returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetTransferList(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetTransferList", args...)
}

// PrivateGetBaseFee returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetBaseFee(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetBaseFee", args...)
}

// PrivateGetTradeFees returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetTradeFees(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetTradeFees", args...)
}

// PrivateGetMarketOrderbookLevelLevel returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarketOrderbookLevelLevel(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarketOrderbookLevelLevel", args...)
}

// PrivateGetMarketOrderbookLevel2 returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarketOrderbookLevel2(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarketOrderbookLevel2", args...)
}

// PrivateGetMarketOrderbookLevel3 returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarketOrderbookLevel3(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarketOrderbookLevel3", args...)
}

// PrivateGetHfAccountsOpened returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfAccountsOpened(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfAccountsOpened", args...)
}

// PrivateGetHfOrdersActive returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfOrdersActive(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfOrdersActive", args...)
}

// PrivateGetHfOrdersActiveSymbols returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfOrdersActiveSymbols(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfOrdersActiveSymbols", args...)
}

// PrivateGetHfMarginOrderActiveSymbols returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOrderActiveSymbols(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOrderActiveSymbols", args...)
}

// PrivateGetHfOrdersDone returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfOrdersDone(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfOrdersDone", args...)
}

// PrivateGetHfOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfOrdersOrderId", args...)
}

// PrivateGetHfOrdersClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfOrdersClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfOrdersClientOrderClientOid", args...)
}

// PrivateGetHfOrdersDeadCancelAllQuery returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfOrdersDeadCancelAllQuery(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfOrdersDeadCancelAllQuery", args...)
}

// PrivateGetHfFills returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfFills(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfFills", args...)
}

// PrivateGetOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetOrders", args...)
}

// PrivateGetLimitOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetLimitOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetLimitOrders", args...)
}

// PrivateGetOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetOrdersOrderId", args...)
}

// PrivateGetOrderClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetOrderClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetOrderClientOrderClientOid", args...)
}

// PrivateGetFills returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetFills(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetFills", args...)
}

// PrivateGetLimitFills returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetLimitFills(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetLimitFills", args...)
}

// PrivateGetStopOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetStopOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetStopOrder", args...)
}

// PrivateGetStopOrderOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetStopOrderOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetStopOrderOrderId", args...)
}

// PrivateGetStopOrderQueryOrderByClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetStopOrderQueryOrderByClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetStopOrderQueryOrderByClientOid", args...)
}

// PrivateGetOcoOrderOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetOcoOrderOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetOcoOrderOrderId", args...)
}

// PrivateGetOcoOrderDetailsOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetOcoOrderDetailsOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetOcoOrderDetailsOrderId", args...)
}

// PrivateGetOcoClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetOcoClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetOcoClientOrderClientOid", args...)
}

// PrivateGetOcoOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetOcoOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetOcoOrders", args...)
}

// PrivateGetHfMarginOrdersActive returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOrdersActive(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOrdersActive", args...)
}

// PrivateGetHfMarginOrdersDone returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOrdersDone(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOrdersDone", args...)
}

// PrivateGetHfMarginOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOrdersOrderId", args...)
}

// PrivateGetHfMarginOrdersClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOrdersClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOrdersClientOrderClientOid", args...)
}

// PrivateGetHfMarginFills returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginFills(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginFills", args...)
}

// PrivateGetHfMarginStopOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginStopOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginStopOrders", args...)
}

// PrivateGetHfMarginStopOrderOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginStopOrderOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginStopOrderOrderId", args...)
}

// PrivateGetHfMarginStopOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginStopOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginStopOrderClientOid", args...)
}

// PrivateGetHfMarginOcoOrderOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOcoOrderOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOcoOrderOrderId", args...)
}

// PrivateGetHfMarginOcoOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOcoOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOcoOrderClientOid", args...)
}

// PrivateGetHfMarginOcoOrderDetailOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOcoOrderDetailOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOcoOrderDetailOrderId", args...)
}

// PrivateGetHfMarginOcoOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetHfMarginOcoOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetHfMarginOcoOrders", args...)
}

// PrivateGetEtfInfo returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetEtfInfo(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetEtfInfo", args...)
}

// PrivateGetMarginCurrencies returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarginCurrencies(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarginCurrencies", args...)
}

// PrivateGetRiskLimitStrategy returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetRiskLimitStrategy(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetRiskLimitStrategy", args...)
}

// PrivateGetIsolatedSymbols returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetIsolatedSymbols(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetIsolatedSymbols", args...)
}

// PrivateGetMarginSymbols returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarginSymbols(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarginSymbols", args...)
}

// PrivateGetIsolatedAccountSymbol returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetIsolatedAccountSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetIsolatedAccountSymbol", args...)
}

// PrivateGetMarginBorrow returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarginBorrow(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarginBorrow", args...)
}

// PrivateGetMarginRepay returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarginRepay(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarginRepay", args...)
}

// PrivateGetMarginInterest returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMarginInterest(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMarginInterest", args...)
}

// PrivateGetProjectList returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetProjectList(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetProjectList", args...)
}

// PrivateGetProjectMarketInterestRate returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetProjectMarketInterestRate(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetProjectMarketInterestRate", args...)
}

// PrivateGetRedeemOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetRedeemOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetRedeemOrders", args...)
}

// PrivateGetPurchaseOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetPurchaseOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetPurchaseOrders", args...)
}

// PrivateGetBrokerApiRebaseDownload returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetBrokerApiRebaseDownload(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetBrokerApiRebaseDownload", args...)
}

// PrivateGetBrokerQueryMyCommission returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetBrokerQueryMyCommission(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetBrokerQueryMyCommission", args...)
}

// PrivateGetBrokerQueryUser returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetBrokerQueryUser(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetBrokerQueryUser", args...)
}

// PrivateGetBrokerQueryDetailByUid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetBrokerQueryDetailByUid(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetBrokerQueryDetailByUid", args...)
}

// PrivateGetMigrateUserAccountStatus returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetMigrateUserAccountStatus(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetMigrateUserAccountStatus", args...)
}

// PrivateGetConvertQuote returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetConvertQuote(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetConvertQuote", args...)
}

// PrivateGetConvertOrderDetail returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetConvertOrderDetail(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetConvertOrderDetail", args...)
}

// PrivateGetConvertOrderHistory returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetConvertOrderHistory(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetConvertOrderHistory", args...)
}

// PrivateGetConvertLimitQuote returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetConvertLimitQuote(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetConvertLimitQuote", args...)
}

// PrivateGetConvertLimitOrderDetail returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetConvertLimitOrderDetail(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetConvertLimitOrderDetail", args...)
}

// PrivateGetConvertLimitOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetConvertLimitOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetConvertLimitOrders", args...)
}

// PrivateGetAffiliateInviterStatistics returns a channel that yields a JSON object.
func (this *CexcCore) PrivateGetAffiliateInviterStatistics(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetAffiliateInviterStatistics", args...)
}

// PrivatePostSubUserCreated returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostSubUserCreated(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostSubUserCreated", args...)
}

// PrivatePostSubApiKey returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostSubApiKey(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostSubApiKey", args...)
}

// PrivatePostSubApiKeyUpdate returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostSubApiKeyUpdate(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostSubApiKeyUpdate", args...)
}

// PrivatePostDepositAddresses returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostDepositAddresses(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostDepositAddresses", args...)
}

// PrivatePostWithdrawals returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostWithdrawals(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostWithdrawals", args...)
}

// PrivatePostAccountsUniversalTransfer returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostAccountsUniversalTransfer(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostAccountsUniversalTransfer", args...)
}

// PrivatePostAccountsSubTransfer returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostAccountsSubTransfer(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostAccountsSubTransfer", args...)
}

// PrivatePostAccountsInnerTransfer returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostAccountsInnerTransfer(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostAccountsInnerTransfer", args...)
}

// PrivatePostTransferOut returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostTransferOut(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostTransferOut", args...)
}

// PrivatePostTransferIn returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostTransferIn(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostTransferIn", args...)
}

// PrivatePostHfOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfOrders", args...)
}

// PrivatePostHfOrdersTest returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfOrdersTest(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfOrdersTest", args...)
}

// PrivatePostHfOrdersSync returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfOrdersSync(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfOrdersSync", args...)
}

// PrivatePostHfOrdersMulti returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfOrdersMulti(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfOrdersMulti", args...)
}

// PrivatePostHfOrdersMultiSync returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfOrdersMultiSync(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfOrdersMultiSync", args...)
}

// PrivatePostHfOrdersAlter returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfOrdersAlter(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfOrdersAlter", args...)
}

// PrivatePostHfOrdersDeadCancelAll returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfOrdersDeadCancelAll(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfOrdersDeadCancelAll", args...)
}

// PrivatePostOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostOrders", args...)
}

// PrivatePostOrdersTest returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostOrdersTest(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostOrdersTest", args...)
}

// PrivatePostOrdersMulti returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostOrdersMulti(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostOrdersMulti", args...)
}

// PrivatePostStopOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostStopOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostStopOrder", args...)
}

// PrivatePostOcoOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostOcoOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostOcoOrder", args...)
}

// PrivatePostHfMarginOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfMarginOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfMarginOrder", args...)
}

// PrivatePostHfMarginOrderTest returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfMarginOrderTest(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfMarginOrderTest", args...)
}

// PrivatePostHfMarginStopOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfMarginStopOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfMarginStopOrder", args...)
}

// PrivatePostMarginOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostMarginOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarginOrder", args...)
}

// PrivatePostMarginOrderTest returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostMarginOrderTest(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarginOrderTest", args...)
}

// PrivatePostHfMarginOcoOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostHfMarginOcoOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostHfMarginOcoOrder", args...)
}

// PrivatePostMarginBorrow returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostMarginBorrow(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarginBorrow", args...)
}

// PrivatePostMarginRepay returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostMarginRepay(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarginRepay", args...)
}

// PrivatePostPurchase returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostPurchase(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostPurchase", args...)
}

// PrivatePostRedeem returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostRedeem(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostRedeem", args...)
}

// PrivatePostLendPurchaseUpdate returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostLendPurchaseUpdate(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostLendPurchaseUpdate", args...)
}

// PrivatePostConvertOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostConvertOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostConvertOrder", args...)
}

// PrivatePostConvertLimitOrder returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostConvertLimitOrder(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostConvertLimitOrder", args...)
}

// PrivatePostBulletPrivate returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostBulletPrivate(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostBulletPrivate", args...)
}

// PrivatePostPositionUpdateUserLeverage returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostPositionUpdateUserLeverage(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostPositionUpdateUserLeverage", args...)
}

// PrivatePostDepositAddressCreate returns a channel that yields a JSON object.
func (this *CexcCore) PrivatePostDepositAddressCreate(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostDepositAddressCreate", args...)
}

// PrivateDeleteSubApiKey returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteSubApiKey(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteSubApiKey", args...)
}

// PrivateDeleteWithdrawalsWithdrawalId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteWithdrawalsWithdrawalId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteWithdrawalsWithdrawalId", args...)
}

// PrivateDeleteHfOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfOrdersOrderId", args...)
}

// PrivateDeleteHfOrdersSyncOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfOrdersSyncOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfOrdersSyncOrderId", args...)
}

// PrivateDeleteHfOrdersClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfOrdersClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfOrdersClientOrderClientOid", args...)
}

// PrivateDeleteHfOrdersSyncClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfOrdersSyncClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfOrdersSyncClientOrderClientOid", args...)
}

// PrivateDeleteHfOrdersCancelOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfOrdersCancelOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfOrdersCancelOrderId", args...)
}

// PrivateDeleteHfOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfOrders", args...)
}

// PrivateDeleteHfOrdersCancelAll returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfOrdersCancelAll(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfOrdersCancelAll", args...)
}

// PrivateDeleteOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteOrdersOrderId", args...)
}

// PrivateDeleteOrderClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteOrderClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteOrderClientOrderClientOid", args...)
}

// PrivateDeleteOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteOrders", args...)
}

// PrivateDeleteStopOrderOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteStopOrderOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteStopOrderOrderId", args...)
}

// PrivateDeleteStopOrderCancelOrderByClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteStopOrderCancelOrderByClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteStopOrderCancelOrderByClientOid", args...)
}

// PrivateDeleteStopOrderCancel returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteStopOrderCancel(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteStopOrderCancel", args...)
}

// PrivateDeleteOcoOrderOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteOcoOrderOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteOcoOrderOrderId", args...)
}

// PrivateDeleteOcoClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteOcoClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteOcoClientOrderClientOid", args...)
}

// PrivateDeleteOcoOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteOcoOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteOcoOrders", args...)
}

// PrivateDeleteHfMarginOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginOrdersOrderId", args...)
}

// PrivateDeleteHfMarginOrdersClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginOrdersClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginOrdersClientOrderClientOid", args...)
}

// PrivateDeleteHfMarginOrders returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginOrders", args...)
}

// PrivateDeleteHfMarginStopOrderCancelById returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginStopOrderCancelById(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginStopOrderCancelById", args...)
}

// PrivateDeleteHfMarginStopOrderCancelByClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginStopOrderCancelByClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginStopOrderCancelByClientOid", args...)
}

// PrivateDeleteHfMarginStopOrderCancel returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginStopOrderCancel(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginStopOrderCancel", args...)
}

// PrivateDeleteHfMarginOcoOrderCancelById returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginOcoOrderCancelById(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginOcoOrderCancelById", args...)
}

// PrivateDeleteHfMarginOcoOrderCancelByClientOid returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginOcoOrderCancelByClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginOcoOrderCancelByClientOid", args...)
}

// PrivateDeleteHfMarginOcoOrderCancel returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteHfMarginOcoOrderCancel(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteHfMarginOcoOrderCancel", args...)
}

// PrivateDeleteConvertLimitOrderCancel returns a channel that yields a JSON object.
func (this *CexcCore) PrivateDeleteConvertLimitOrderCancel(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteConvertLimitOrderCancel", args...)
}

// FuturesPublicGetContractsActive returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetContractsActive(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetContractsActive", args...)
}

// FuturesPublicGetContractsSymbol returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetContractsSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetContractsSymbol", args...)
}

// FuturesPublicGetTicker returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetTicker(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetTicker", args...)
}

// FuturesPublicGetAllTickers returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetAllTickers(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetAllTickers", args...)
}

// FuturesPublicGetLevel2Snapshot returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetLevel2Snapshot(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetLevel2Snapshot", args...)
}

// FuturesPublicGetLevel2Depth20 returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetLevel2Depth20(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetLevel2Depth20", args...)
}

// FuturesPublicGetLevel2Depth100 returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetLevel2Depth100(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetLevel2Depth100", args...)
}

// FuturesPublicGetTradeHistory returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetTradeHistory(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetTradeHistory", args...)
}

// FuturesPublicGetKlineQuery returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetKlineQuery(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetKlineQuery", args...)
}

// FuturesPublicGetInterestQuery returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetInterestQuery(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetInterestQuery", args...)
}

// FuturesPublicGetIndexQuery returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetIndexQuery(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetIndexQuery", args...)
}

// FuturesPublicGetMarkPriceSymbolCurrent returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetMarkPriceSymbolCurrent(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetMarkPriceSymbolCurrent", args...)
}

// FuturesPublicGetPremiumQuery returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetPremiumQuery(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetPremiumQuery", args...)
}

// FuturesPublicGetTradeStatistics returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetTradeStatistics(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetTradeStatistics", args...)
}

// FuturesPublicGetFundingRateSymbolCurrent returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetFundingRateSymbolCurrent(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetFundingRateSymbolCurrent", args...)
}

// FuturesPublicGetContractFundingRates returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetContractFundingRates(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetContractFundingRates", args...)
}

// FuturesPublicGetTimestamp returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetTimestamp(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetTimestamp", args...)
}

// FuturesPublicGetStatus returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetStatus(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetStatus", args...)
}

// FuturesPublicGetLevel2MessageQuery returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetLevel2MessageQuery(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetLevel2MessageQuery", args...)
}

// FuturesPublicGetContractsRiskLimitSymbol returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetContractsRiskLimitSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetContractsRiskLimitSymbol", args...)
}

// FuturesPublicGetLevel3MessageQuery returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetLevel3MessageQuery(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetLevel3MessageQuery", args...)
}

// FuturesPublicGetLevel3Snapshot returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicGetLevel3Snapshot(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicGetLevel3Snapshot", args...)
}

// FuturesPublicPostBulletPublic returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPublicPostBulletPublic(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPublicPostBulletPublic", args...)
}

// FuturesPrivateGetTransactionHistory returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetTransactionHistory(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetTransactionHistory", args...)
}

// FuturesPrivateGetAccountOverview returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetAccountOverview(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetAccountOverview", args...)
}

// FuturesPrivateGetAccountOverviewAll returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetAccountOverviewAll(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetAccountOverviewAll", args...)
}

// FuturesPrivateGetTransferList returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetTransferList(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetTransferList", args...)
}

// FuturesPrivateGetOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetOrders", args...)
}

// FuturesPrivateGetStopOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetStopOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetStopOrders", args...)
}

// FuturesPrivateGetRecentDoneOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetRecentDoneOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetRecentDoneOrders", args...)
}

// FuturesPrivateGetOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetOrdersOrderId", args...)
}

// FuturesPrivateGetOrdersByClientOid returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetOrdersByClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetOrdersByClientOid", args...)
}

// FuturesPrivateGetFills returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetFills(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetFills", args...)
}

// FuturesPrivateGetRecentFills returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetRecentFills(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetRecentFills", args...)
}

// FuturesPrivateGetTradeFees returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetTradeFees(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetTradeFees", args...)
}

// FuturesPrivateGetOpenOrderStatistics returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetOpenOrderStatistics(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetOpenOrderStatistics", args...)
}

// FuturesPrivateGetPosition returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetPosition(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetPosition", args...)
}

// FuturesPrivateGetPositions returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetPositions(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetPositions", args...)
}

// FuturesPrivateGetMarginMaxWithdrawMargin returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetMarginMaxWithdrawMargin(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetMarginMaxWithdrawMargin", args...)
}

// FuturesPrivateGetContractsRiskLimitSymbol returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetContractsRiskLimitSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetContractsRiskLimitSymbol", args...)
}

// FuturesPrivateGetFundingHistory returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetFundingHistory(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetFundingHistory", args...)
}

// FuturesPrivateGetCopyTradeFuturesGetMaxOpenSize returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetCopyTradeFuturesGetMaxOpenSize(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetCopyTradeFuturesGetMaxOpenSize", args...)
}

// FuturesPrivateGetCopyTradeFuturesPositionMarginMaxWithdrawMargin returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetCopyTradeFuturesPositionMarginMaxWithdrawMargin(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetCopyTradeFuturesPositionMarginMaxWithdrawMargin", args...)
}

// FuturesPrivateGetHistoryPositions returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetHistoryPositions(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetHistoryPositions", args...)
}

// FuturesPrivateGetPositionGetMarginMode returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetPositionGetMarginMode(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetPositionGetMarginMode", args...)
}

// FuturesPrivateGetPositionGetPositionMode returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetPositionGetPositionMode(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetPositionGetPositionMode", args...)
}

// FuturesPrivateGetDepositAddress returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetDepositAddress(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetDepositAddress", args...)
}

// FuturesPrivateGetDepositList returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetDepositList(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetDepositList", args...)
}

// FuturesPrivateGetWithdrawalsQuotas returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetWithdrawalsQuotas(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetWithdrawalsQuotas", args...)
}

// FuturesPrivateGetWithdrawalList returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetWithdrawalList(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetWithdrawalList", args...)
}

// FuturesPrivateGetSubApiKey returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetSubApiKey(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetSubApiKey", args...)
}

// FuturesPrivateGetTradeStatistics returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetTradeStatistics(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetTradeStatistics", args...)
}

// FuturesPrivateGetGetMaxOpenSize returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetGetMaxOpenSize(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetGetMaxOpenSize", args...)
}

// FuturesPrivateGetGetCrossUserLeverage returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateGetGetCrossUserLeverage(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateGetGetCrossUserLeverage", args...)
}

// FuturesPrivatePostTransferOut returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostTransferOut(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostTransferOut", args...)
}

// FuturesPrivatePostTransferIn returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostTransferIn(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostTransferIn", args...)
}

// FuturesPrivatePostOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostOrders", args...)
}

// FuturesPrivatePostStOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostStOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostStOrders", args...)
}

// FuturesPrivatePostOrdersTest returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostOrdersTest(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostOrdersTest", args...)
}

// FuturesPrivatePostOrdersMulti returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostOrdersMulti(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostOrdersMulti", args...)
}

// FuturesPrivatePostPositionMarginAutoDepositStatus returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostPositionMarginAutoDepositStatus(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostPositionMarginAutoDepositStatus", args...)
}

// FuturesPrivatePostMarginWithdrawMargin returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostMarginWithdrawMargin(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostMarginWithdrawMargin", args...)
}

// FuturesPrivatePostPositionMarginDepositMargin returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostPositionMarginDepositMargin(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostPositionMarginDepositMargin", args...)
}

// FuturesPrivatePostPositionRiskLimitLevelChange returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostPositionRiskLimitLevelChange(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostPositionRiskLimitLevelChange", args...)
}

// FuturesPrivatePostCopyTradeFuturesOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesOrders", args...)
}

// FuturesPrivatePostCopyTradeFuturesOrdersTest returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesOrdersTest(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesOrdersTest", args...)
}

// FuturesPrivatePostCopyTradeFuturesStOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesStOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesStOrders", args...)
}

// FuturesPrivatePostCopyTradeFuturesPositionMarginDepositMargin returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesPositionMarginDepositMargin(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesPositionMarginDepositMargin", args...)
}

// FuturesPrivatePostCopyTradeFuturesPositionMarginWithdrawMargin returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesPositionMarginWithdrawMargin(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesPositionMarginWithdrawMargin", args...)
}

// FuturesPrivatePostCopyTradeFuturesPositionRiskLimitLevelChange returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesPositionRiskLimitLevelChange(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesPositionRiskLimitLevelChange", args...)
}

// FuturesPrivatePostCopyTradeFuturesPositionMarginAutoDepositStatus returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesPositionMarginAutoDepositStatus(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesPositionMarginAutoDepositStatus", args...)
}

// FuturesPrivatePostCopyTradeFuturesPositionChangeMarginMode returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesPositionChangeMarginMode(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesPositionChangeMarginMode", args...)
}

// FuturesPrivatePostCopyTradeFuturesPositionChangeCrossUserLeverage returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeFuturesPositionChangeCrossUserLeverage(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeFuturesPositionChangeCrossUserLeverage", args...)
}

// FuturesPrivatePostCopyTradeGetCrossModeMarginRequirement returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradeGetCrossModeMarginRequirement(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradeGetCrossModeMarginRequirement", args...)
}

// FuturesPrivatePostCopyTradePositionSwitchPositionMode returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostCopyTradePositionSwitchPositionMode(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostCopyTradePositionSwitchPositionMode", args...)
}

// FuturesPrivatePostChangeCrossUserLeverage returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostChangeCrossUserLeverage(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostChangeCrossUserLeverage", args...)
}

// FuturesPrivatePostWithdrawals returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostWithdrawals(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostWithdrawals", args...)
}

// FuturesPrivatePostSubApiKey returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostSubApiKey(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostSubApiKey", args...)
}

// FuturesPrivatePostSubApiKeyUpdate returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostSubApiKeyUpdate(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostSubApiKeyUpdate", args...)
}

// FuturesPrivatePostPositionChangeMarginMode returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostPositionChangeMarginMode(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostPositionChangeMarginMode", args...)
}

// FuturesPrivatePostPositionSwitchPositionMode returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostPositionSwitchPositionMode(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostPositionSwitchPositionMode", args...)
}

// FuturesPrivatePostBulletPrivate returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivatePostBulletPrivate(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivatePostBulletPrivate", args...)
}

// FuturesPrivateDeleteOrdersOrderId returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteOrdersOrderId(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteOrdersOrderId", args...)
}

// FuturesPrivateDeleteOrdersClientOrderClientOid returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteOrdersClientOrderClientOid(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteOrdersClientOrderClientOid", args...)
}

// FuturesPrivateDeleteOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteOrders", args...)
}

// FuturesPrivateDeleteStopOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteStopOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteStopOrders", args...)
}

// FuturesPrivateDeleteCopyTradeFuturesOrders returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteCopyTradeFuturesOrders(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteCopyTradeFuturesOrders", args...)
}

// FuturesPrivateDeleteCopyTradeFuturesOrdersClientOrder returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteCopyTradeFuturesOrdersClientOrder(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteCopyTradeFuturesOrdersClientOrder", args...)
}

// FuturesPrivateDeleteOrdersMultiCancel returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteOrdersMultiCancel(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteOrdersMultiCancel", args...)
}

// FuturesPrivateDeleteWithdrawalsWithdrawalId returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteWithdrawalsWithdrawalId(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteWithdrawalsWithdrawalId", args...)
}

// FuturesPrivateDeleteCancelTransferOut returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteCancelTransferOut(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteCancelTransferOut", args...)
}

// FuturesPrivateDeleteSubApiKey returns a channel that yields a JSON object.
func (this *CexcCore) FuturesPrivateDeleteSubApiKey(args ...any) <-chan any {
	return this.callEndpointAsync("futuresPrivateDeleteSubApiKey", args...)
}

// WebExchangeGetCurrencyCurrencyChainInfo returns a channel that yields a JSON object.
func (this *CexcCore) WebExchangeGetCurrencyCurrencyChainInfo(args ...any) <-chan any {
	return this.callEndpointAsync("webExchangeGetCurrencyCurrencyChainInfo", args...)
}

// WebExchangeGetContractSymbolFundingRates returns a channel that yields a JSON object.
func (this *CexcCore) WebExchangeGetContractSymbolFundingRates(args ...any) <-chan any {
	return this.callEndpointAsync("webExchangeGetContractSymbolFundingRates", args...)
}

// BrokerGetBrokerNdInfo returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetBrokerNdInfo(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetBrokerNdInfo", args...)
}

// BrokerGetBrokerNdAccount returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetBrokerNdAccount(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetBrokerNdAccount", args...)
}

// BrokerGetBrokerNdAccountApikey returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetBrokerNdAccountApikey(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetBrokerNdAccountApikey", args...)
}

// BrokerGetBrokerNdRebaseDownload returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetBrokerNdRebaseDownload(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetBrokerNdRebaseDownload", args...)
}

// BrokerGetAssetNdbrokerDepositList returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetAssetNdbrokerDepositList(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetAssetNdbrokerDepositList", args...)
}

// BrokerGetBrokerNdTransferDetail returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetBrokerNdTransferDetail(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetBrokerNdTransferDetail", args...)
}

// BrokerGetBrokerNdDepositDetail returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetBrokerNdDepositDetail(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetBrokerNdDepositDetail", args...)
}

// BrokerGetBrokerNdWithdrawDetail returns a channel that yields a JSON object.
func (this *CexcCore) BrokerGetBrokerNdWithdrawDetail(args ...any) <-chan any {
	return this.callEndpointAsync("brokerGetBrokerNdWithdrawDetail", args...)
}

// BrokerPostBrokerNdTransfer returns a channel that yields a JSON object.
func (this *CexcCore) BrokerPostBrokerNdTransfer(args ...any) <-chan any {
	return this.callEndpointAsync("brokerPostBrokerNdTransfer", args...)
}

// BrokerPostBrokerNdAccount returns a channel that yields a JSON object.
func (this *CexcCore) BrokerPostBrokerNdAccount(args ...any) <-chan any {
	return this.callEndpointAsync("brokerPostBrokerNdAccount", args...)
}

// BrokerPostBrokerNdAccountApikey returns a channel that yields a JSON object.
func (this *CexcCore) BrokerPostBrokerNdAccountApikey(args ...any) <-chan any {
	return this.callEndpointAsync("brokerPostBrokerNdAccountApikey", args...)
}

// BrokerPostBrokerNdAccountUpdateApikey returns a channel that yields a JSON object.
func (this *CexcCore) BrokerPostBrokerNdAccountUpdateApikey(args ...any) <-chan any {
	return this.callEndpointAsync("brokerPostBrokerNdAccountUpdateApikey", args...)
}

// BrokerDeleteBrokerNdAccountApikey returns a channel that yields a JSON object.
func (this *CexcCore) BrokerDeleteBrokerNdAccountApikey(args ...any) <-chan any {
	return this.callEndpointAsync("brokerDeleteBrokerNdAccountApikey", args...)
}

// EarnGetOtcLoanDiscountRateConfigs returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetOtcLoanDiscountRateConfigs(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetOtcLoanDiscountRateConfigs", args...)
}

// EarnGetOtcLoanLoan returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetOtcLoanLoan(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetOtcLoanLoan", args...)
}

// EarnGetOtcLoanAccounts returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetOtcLoanAccounts(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetOtcLoanAccounts", args...)
}

// EarnGetEarnRedeemPreview returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetEarnRedeemPreview(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetEarnRedeemPreview", args...)
}

// EarnGetEarnSavingProducts returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetEarnSavingProducts(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetEarnSavingProducts", args...)
}

// EarnGetEarnHoldAssets returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetEarnHoldAssets(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetEarnHoldAssets", args...)
}

// EarnGetEarnPromotionProducts returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetEarnPromotionProducts(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetEarnPromotionProducts", args...)
}

// EarnGetEarnKcsStakingProducts returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetEarnKcsStakingProducts(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetEarnKcsStakingProducts", args...)
}

// EarnGetEarnStakingProducts returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetEarnStakingProducts(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetEarnStakingProducts", args...)
}

// EarnGetEarnEthStakingProducts returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetEarnEthStakingProducts(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetEarnEthStakingProducts", args...)
}

// EarnGetStructEarnDualProducts returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetStructEarnDualProducts(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetStructEarnDualProducts", args...)
}

// EarnGetStructEarnOrders returns a channel that yields a JSON object.
func (this *CexcCore) EarnGetStructEarnOrders(args ...any) <-chan any {
	return this.callEndpointAsync("earnGetStructEarnOrders", args...)
}

// EarnPostEarnOrders returns a channel that yields a JSON object.
func (this *CexcCore) EarnPostEarnOrders(args ...any) <-chan any {
	return this.callEndpointAsync("earnPostEarnOrders", args...)
}

// EarnPostStructEarnOrders returns a channel that yields a JSON object.
func (this *CexcCore) EarnPostStructEarnOrders(args ...any) <-chan any {
	return this.callEndpointAsync("earnPostStructEarnOrders", args...)
}

// EarnDeleteEarnOrders returns a channel that yields a JSON object.
func (this *CexcCore) EarnDeleteEarnOrders(args ...any) <-chan any {
	return this.callEndpointAsync("earnDeleteEarnOrders", args...)
}

// UtaGetMarketAnnouncement returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketAnnouncement(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketAnnouncement", args...)
}

// UtaGetMarketCurrency returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketCurrency(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketCurrency", args...)
}

// UtaGetAssetCurrencies returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetAssetCurrencies(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetAssetCurrencies", args...)
}

// UtaGetMarketInstrument returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketInstrument(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketInstrument", args...)
}

// UtaGetMarketTicker returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketTicker(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketTicker", args...)
}

// UtaGetMarketTrade returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketTrade(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketTrade", args...)
}

// UtaGetMarketKline returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketKline(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketKline", args...)
}

// UtaGetMarketFundingRate returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketFundingRate(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketFundingRate", args...)
}

// UtaGetMarketFundingRateHistory returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketFundingRateHistory(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketFundingRateHistory", args...)
}

// UtaGetMarketCrossConfig returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketCrossConfig(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketCrossConfig", args...)
}

// UtaGetMarketCollateralDiscountRatio returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketCollateralDiscountRatio(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketCollateralDiscountRatio", args...)
}

// UtaGetMarketIndexPrice returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketIndexPrice(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketIndexPrice", args...)
}

// UtaGetMarketPositionTiers returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketPositionTiers(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketPositionTiers", args...)
}

// UtaGetMarketOpenInterest returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketOpenInterest(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketOpenInterest", args...)
}

// UtaGetServerStatus returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetServerStatus(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetServerStatus", args...)
}

// UtaGetMarketBorrowableCurrency returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketBorrowableCurrency(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketBorrowableCurrency", args...)
}

// UtaGetUserMyIp returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetUserMyIp(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetUserMyIp", args...)
}

// UtaGetMarketFiatPrice returns a channel that yields a JSON object.
func (this *CexcCore) UtaGetMarketFiatPrice(args ...any) <-chan any {
	return this.callEndpointAsync("utaGetMarketFiatPrice", args...)
}

// UtaPrivateGetMarketOrderbook returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetMarketOrderbook(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetMarketOrderbook", args...)
}

// UtaPrivateGetAccountBalance returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountBalance(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountBalance", args...)
}

// UtaPrivateGetAccountTransferQuota returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountTransferQuota(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountTransferQuota", args...)
}

// UtaPrivateGetAccountMode returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountMode(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountMode", args...)
}

// UtaPrivateGetAccountLedger returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountLedger(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountLedger", args...)
}

// UtaPrivateGetAccountInterestHistory returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountInterestHistory(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountInterestHistory", args...)
}

// UtaPrivateGetAssetDepositAddress returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAssetDepositAddress(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAssetDepositAddress", args...)
}

// UtaPrivateGetAccountDepositAddress returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountDepositAddress(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountDepositAddress", args...)
}

// UtaPrivateGetAccountModeAccountBalance returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModeAccountBalance(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModeAccountBalance", args...)
}

// UtaPrivateGetAccountModeAccountOverview returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModeAccountOverview(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModeAccountOverview", args...)
}

// UtaPrivateGetAccountModeOrderDetail returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModeOrderDetail(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModeOrderDetail", args...)
}

// UtaPrivateGetAccountModeOrderOpenList returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModeOrderOpenList(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModeOrderOpenList", args...)
}

// UtaPrivateGetAccountModeOrderHistory returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModeOrderHistory(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModeOrderHistory", args...)
}

// UtaPrivateGetAccountModeOrderExecution returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModeOrderExecution(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModeOrderExecution", args...)
}

// UtaPrivateGetAccountModePositionOpenList returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModePositionOpenList(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModePositionOpenList", args...)
}

// UtaPrivateGetAccountModePositionHistory returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModePositionHistory(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModePositionHistory", args...)
}

// UtaPrivateGetPositionHistory returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetPositionHistory(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetPositionHistory", args...)
}

// UtaPrivateGetAccountModePositionTiers returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountModePositionTiers(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountModePositionTiers", args...)
}

// UtaPrivateGetSubAccountBalance returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetSubAccountBalance(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetSubAccountBalance", args...)
}

// UtaPrivateGetUserFeeRate returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetUserFeeRate(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetUserFeeRate", args...)
}

// UtaPrivateGetDcpQuery returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetDcpQuery(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetDcpQuery", args...)
}

// UtaPrivateGetUnifiedAccountLeverage returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetUnifiedAccountLeverage(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetUnifiedAccountLeverage", args...)
}

// UtaPrivateGetPositionFundingHistory returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetPositionFundingHistory(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetPositionFundingHistory", args...)
}

// UtaPrivateGetAccountInterestLimits returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivateGetAccountInterestLimits(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivateGetAccountInterestLimits", args...)
}

// UtaPrivatePostAccountTransfer returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountTransfer(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountTransfer", args...)
}

// UtaPrivatePostAccountMode returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountMode(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountMode", args...)
}

// UtaPrivatePostAccountModeAccountModifyLeverage returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountModeAccountModifyLeverage(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountModeAccountModifyLeverage", args...)
}

// UtaPrivatePostAccountModeOrderPlace returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountModeOrderPlace(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountModeOrderPlace", args...)
}

// UtaPrivatePostAccountModeOrderPlaceBatch returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountModeOrderPlaceBatch(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountModeOrderPlaceBatch", args...)
}

// UtaPrivatePostAccountModeOrderCancel returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountModeOrderCancel(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountModeOrderCancel", args...)
}

// UtaPrivatePostAccountModeOrderCancelBatch returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountModeOrderCancelBatch(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountModeOrderCancelBatch", args...)
}

// UtaPrivatePostAccountModeOrderCancelAll returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountModeOrderCancelAll(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountModeOrderCancelAll", args...)
}

// UtaPrivatePostSubAccountCanTransferOut returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostSubAccountCanTransferOut(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostSubAccountCanTransferOut", args...)
}

// UtaPrivatePostDcpSet returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostDcpSet(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostDcpSet", args...)
}

// UtaPrivatePostAccountModeAccountModifyLeverageMarginCross returns a channel that yields a JSON object.
func (this *CexcCore) UtaPrivatePostAccountModeAccountModifyLeverageMarginCross(args ...any) <-chan any {
	return this.callEndpointAsync("utaPrivatePostAccountModeAccountModifyLeverageMarginCross", args...)
}
